CREATE TABLE IF NOT EXISTS clients (
    id INT AUTO_INCREMENT PRIMARY KEY,
    client_name VARCHAR(255) NOT NULL,
    address TEXT NULL,
    pay_day INT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

ALTER TABLE invoices
    ADD COLUMN client_id INT NULL AFTER id,
    ADD COLUMN invoice_number VARCHAR(100) NULL AFTER client_id,
    ADD COLUMN hours DECIMAL(10,2) NULL AFTER task_details,
    ADD COLUMN rate DECIMAL(10,2) NULL AFTER hours,
    ADD COLUMN tax_rate DECIMAL(5,2) NOT NULL DEFAULT 18.00 AFTER rate,
    ADD COLUMN subtotal DECIMAL(15,2) NULL AFTER tax_rate;

ALTER TABLE invoices
    ADD CONSTRAINT fk_inv_client FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL;

ALTER TABLE invoices
    MODIFY COLUMN project_id INT NULL;
